hubble, install: print command args as string in error message
When a command fails to execute, its args are shown in the slice syntax
which makes it cumbersome to copy&paste said command for further
analysis, e.g.

    Error: Unable to install Cilium:  unable to execute "az [aks show --resource-group foo-test-12960 --name foo-test-12960]": exit status 3

Change the command args to be printed as a space separated string, so
they can be easily copy&pasted from the error message:

    Error: Unable to install Cilium: unable to execute "az aks show --resource-group foo-test-12960 --name foo-test-12960": exit status 3

Signed-off-by: Tobias Klauser <tobias@cilium.io>